name: oops
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - bcftools>=1.17
  - samtools>=1.17
  - tabix
  - whatshap  ## May be removed in the future, but currently used for phasing
  - pandas
  - numpy
  - scipy
  - matplotlib-base
  - pysam
  - awscli
  - wget
